version: 2.1

orbs:
  coveralls: coveralls/coveralls@1.0.4
jobs:
  build:
    docker:
      - image: cimg/node:15.10.0
    steps:
      - checkout
      - run: npm install
      - run:
          name: 'Run Jest and Collect Coverage Reports'
          command: npm test -- --collectCoverage=true
      - coveralls/upload
      - store_artifacts:
          path: coverage
